### ISSUE TITLE
Do not put passwords in PLAIN TEXT in log files.

### ISSUE THREAD

**Issue by albrandwood** [Panda88CO/udi-TeslaPowerWall#4]
Basic security ... You do not need to include passwords in log files.

2021-08-27 20:54:34,836 NodeServer polyinterface      DEBUG    TeslaPWController
:start: {'ACCESS': 'CLOUD', 'CLOUD_USER_PASSWORD': 123Password321', 'CLOUD_USER_EMAIL': 'email@domain.com'}

@shley

**Comment by Panda88CO** [comment]
I am still debugging - would need to keep this private but cannot use with polisy if private :-(
It will get removed once functional - but I am still having issues getting the node to register
